### ISSUE TITLE
OAuth1 client using deprecated Faraday method

### ISSUE THREAD

**Issue by seanstory** [googleapis/signet#204]
#### Environment details

  - OS: MacOS 11.6.1
  - Ruby version: jruby-9.2.16.0
  - Gem name and version: signet 0.14

#### Steps to reproduce

  1. use faraday: `gem 'faraday', '~> 1.8.0'`
  2. create a faraday connection: `@connection = Faraday.new`
  3. create an oauth1 http client: `@http_client = Signet::OAuth1::Client.new(...)`
  4. use the connection when fetching: `@http_client.fetch_protected_resource(:connection => @connection)`
  5. See warn logs:
  
```
[2021-12-08T16:08:28.968Z] WARNING: `Faraday::Request#method` is deprecated; use `#http_method` instead. It will be removed in or after version 2.0.
[2021-12-08T16:08:28.968Z] `Faraday::Request#method` called from /ci/ci_state/ruby_bundle/jruby/2.5.0/gems/signet-0.14.0/lib/signet/oauth_1/client.rb:946:in `generate_authenticated_request'
[2021-12-08T16:08:28.968Z] WARNING: `Faraday::Request#method` is deprecated; use `#http_method` instead. It will be removed in or after version 2.0.
[2021-12-08T16:08:28.968Z] `Faraday::Request#method` called from /ci/ci_state/ruby_bundle/jruby/2.5.0/gems/signet-0.14.0/lib/signet/oauth_1/client.rb:946:in `generate_authenticated_request'
[2021-12-08T16:08:28.968Z] WARNING: `Faraday::Request#method` is deprecated; use `#http_method` instead. It will be removed in or after version 2.0.
[2021-12-08T16:08:28.968Z] `Faraday::Request#method` called from /ci/ci_state/ruby_bundle/jruby/2.5.0/gems/signet-0.14.0/lib/signet/oauth_1/client.rb:946:in `generate_authenticated_request'
```

It seems that the usage of `method` needs to be replaced with `http_method`

**Comment by dazuma** [comment]
Thanks! Yes, this should get updated.
